# Generated by Django 4.2.20 on 2025-05-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamenMedico',
        ),
    ]
